---
title: "Biomes' allometry plotting"
author: "Nguyen Thi Duyen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    standalone: true
    embed-resources: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)

```


```{r include=FALSE}
library(tidyverse)
library(targets)
library(viridis)
library(ggplot2)
options(width=150)
```


# Read in data

```{r}
tallo_wd_df0 <- tar_read(tallo_wd_df0)
unique(tallo_wd_df0$biome)
```


```{r}
# Boreal/montane forest
boreal_ang <- tallo_wd_df0 |> filter(biome == "Boreal/montane forest" & division == "Angiosperm")
boreal_ang

boreal_gym <- tallo_wd_df0 |> filter(biome == "Boreal/montane forest" & division == "Gymnosperm")
boreal_gym


# Tropical rain forest
trop_rain_ang <- tallo_wd_df0 |> filter(biome == "Tropical rain forest" & division == "Angiosperm")
trop_rain_ang

trop_rain_gym <- tallo_wd_df0 |> filter(biome == "Tropical rain forest" & division == "Gymnosperm")
trop_rain_gym

# Temperate broadleaf forest
tem_broad_ang <- tallo_wd_df0 |> filter(biome == "Temperate broadleaf forest" & division == "Angiosperm")
tem_broad_ang

tem_broad_gym <- tallo_wd_df0 |> filter(biome == "Temperate broadleaf forest" & division == "Gymnosperm")
tem_broad_gym

# Tropical savanna
trop_sav_ang <- tallo_wd_df0 |> filter(biome == "Tropical savanna" & division == "Angiosperm")
trop_sav_ang

trop_sav_gym <- tallo_wd_df0 |> filter(biome == "Tropical savanna" & division == "Gymnosperm")
trop_sav_gym

# Temperate grassland
tem_grass_ang <- tallo_wd_df0 |> filter(biome == "Temperate grassland" & division == "Angiosperm")
tem_grass_ang

tem_grass_gym <- tallo_wd_df0 |> filter(biome == "Temperate grassland" & division == "Gymnosperm")
tem_grass_gym

# Temperate conifer forest
tem_coni_ang <- tallo_wd_df0 |> filter(biome == "Temperate conifer forest" & division == "Angiosperm")
tem_coni_ang

tem_coni_gym <- tallo_wd_df0 |> filter(biome == "Temperate conifer forest" & division == "Gymnosperm")
tem_coni_gym

# Mediterranean woodland
medi_ang <- tallo_wd_df0 |> filter(biome == "Mediterranean woodland" & division == "Angiosperm")
medi_ang

medi_gym <- tallo_wd_df0 |> filter(biome == "Mediterranean woodland" & division == "Gymnosperm")
medi_gym

# Tropical dry forest
trop_dry_ang <- tallo_wd_df0 |> filter(biome == "Tropical dry forest" & division == "Angiosperm")
trop_dry_ang

trop_dry_gym <- tallo_wd_df0 |> filter(biome == "Tropical dry forest" & division == "Gymnosperm")
trop_dry_gym


# Dryland
dryland_ang <- tallo_wd_df0 |> filter(biome == "Dryland" & division == "Angiosperm")
dryland_ang

dryland_gym <- tallo_wd_df0 |> filter(biome == "Dryland" & division == "Gymnosperm")
dryland_gym

# Mangrove
mangrove_ang <- tallo_wd_df0 |> filter(biome == "Mangrove" & division == "Angiosperm")
mangrove_ang

mangrove_gym <- tallo_wd_df0 |> filter(biome == "Mangrove" & division == "Gymnosperm")
mangrove_gym

```


# Plotting

```{r}
plot_biome <- function(df, biome_name, division_type) {
  
  biome_df <- df |> filter(biome == biome_name & division == division_type)
  
  cr_dbh_plot <- ggplot() +
    geom_bin2d(data = biome_df, aes(x = dbh, y = cr), bins = 100) +
    scale_fill_viridis_c(option = "D") +
    scale_x_log10() +
    scale_y_log10() +
    labs(x = "DBH (cm)", y = "CR (m)", title = paste("CR-DBH:", division_type, "-", biome_name)) +
    theme_minimal()
  
  h_dbh_plot <- ggplot() +
    geom_bin2d(data = biome_df, aes(x = dbh, y = h), bins = 100) +
    scale_fill_viridis_c(option = "D") +
    scale_x_log10() +
    scale_y_log10() +
    labs(x = "DBH (cm)", y = "H (m)", title = paste("H-DBH:", division_type, "-", biome_name)) +
    theme_minimal()
  
  list(cr_dbh_plot = cr_dbh_plot, h_dbh_plot = h_dbh_plot)
}

tallo_wd_df0 <- tar_read(tallo_wd_df0)

biomes <- c("Boreal/montane forest", "Tropical rain forest", "Temperate broadleaf forest", 
            "Tropical savanna", "Temperate grassland", "Temperate conifer forest", 
            "Mediterranean woodland", "Tropical dry forest", "Dryland", "Mangrove")

for (biome in biomes) {
  
  # Ang
  angiosperm_plots <- plot_biome(tallo_wd_df0, biome, "Angiosperm")
  
  print(angiosperm_plots$cr_dbh_plot)
  
  print(angiosperm_plots$h_dbh_plot)
  
  # Gym
  gymnosperm_plots <- plot_biome(tallo_wd_df0, biome, "Gymnosperm")
  
  print(gymnosperm_plots$cr_dbh_plot)
  
  print(gymnosperm_plots$h_dbh_plot)
}
```

