---
title: "Comparing DBH models"
author: "Nguyen Thi Duyen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: coderpro
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    standalone: true
    embed-resources: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r, include=FALSE}
library(targets)
library(tidyverse)
library(scales)
library(MASS)
options(width = 150)
```


# Read in data

- 

```{r}
tallo_reduced_lr_df_ang_dbh <- tar_read(tallo_reduced_lr_df_ang_cr)
tallo_reduced_lr_df_ang_dbh

ang_df <- tallo_reduced_lr_df_ang_dbh |>
  filter(division == "Angiosperm")

gym_df <- tallo_reduced_lr_df_ang_dbh |>
  filter(division == "Gymnosperm")

angiosperms_df
gymnosperms_df


# tallo_reduced_lr_df_gym_dbh <- tar_read(tallo_reduced_lr_df_gym_dbh)
# tallo_reduced_lr_df_gym_dbh

# angiosperms_df1 <- tallo_reduced_lr_df_gym_dbh |>
#   filter(division == "Angiosperm")

# gymnosperms_df1 <- tallo_reduced_lr_df_gym_dbh |>
#   filter(division == "Gymnosperm")

# angiosperms_df1
# gymnosperms_df1


```

# DBH

## Ang
```{r}
fit_lr_nou_data_ang_dbh <- tar_read(fit_lr_nou_data_ang_dbh)
str(fit_lr_nou_data_ang_dbh)

dbh_ang <- tar_read(fit_lr_nou_summary_pl_ang_dbh)
dbh_ang

dbh_gamma_ang <- dbh_ang |> filter(grepl("gamma", variable))
dbh_gamma_ang

community_log_a_dbh_ang <- dbh_gamma_ang |> filter(variable == "gamma[1]") |> pull(q50)
community_b_dbh_ang <- dbh_gamma_ang |> filter(variable == "gamma[2]") |> pull(q50)

community_c_dbh_ang <- dbh_gamma_ang |> filter(variable == "gamma[3]") |> pull(q50)


head(fit_lr_nou_data_ang_dbh$log_x)

fitted_log_y_dbh_ang <- community_log_a_dbh_ang + community_b_dbh_ang * fit_lr_nou_data_ang_dbh$log_x[,2] + community_c_dbh_ang * fit_lr_nou_data_ang_dbh$log_x[,3]

y_pred_dbh_ang <- exp(fitted_log_y_dbh_ang)

df_dbh_ang <- tibble(y = y_pred_dbh_ang, x1 = exp(fit_lr_nou_data_ang_dbh$log_x[,2]), x2 = exp(fit_lr_nou_data_ang_dbh$log_x[,3]))

head(df_dbh_ang)


ggplot(df_dbh_ang, aes(x = x1, y = y)) +
  geom_point() +
  theme_minimal()

```


```{r}

```


```{r}

```
