---
title: "Divergent transitions (gmm1_nou_h)"
author: "Nguyen Thi Duyen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: coderpro
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    standalone: true
    embed-resources: true
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/workspaces/tree-allometry")
```

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

# Load necessary libraries

```{r}
library(posterior)
library(bayesplot)
library(ggplot2)
library(cmdstanr)
library(targets)
```

# Data loading

```{r}
gmm1_nou_h_diag <- tar_read(fit_nlr_diagnostics_gmm1_nou_h) 
gmm1_nou_h_diag
summary(gmm1_nou_h_diag)
```

# Divergent Iterations

```{r}
# Identify divergent iterations
divergent_iterations <- gmm1_nou_h_diag[gmm1_nou_h_diag$divergent__ == 1, ]
divergent_iterations

```

# Plotting

```{r}
fit <- tar_read(fit_nlr_mcmc_gmm1_nou_h) 
mcmc_samples <- as_draws_array(fit$draws())
mcmc_samples

trace_plot <- mcmc_trace(mcmc_samples, pars = c("gamma[1]", "gamma[2]", "gamma[3]"))

pair_plot <- mcmc_pairs(mcmc_samples, pars = c("gamma[1]", "gamma[2]", "gamma[3]"))

trace_plot
pair_plot
```